name: Example Configuration
stacks:
  gateway:
    configuration:
      url: git@github.com:msplat/gateway-configuration.git
    api:
      url: git@github.com:msplat/gateway-api.git

    docker-spy:
      url: git@github.com:msplat/docker-spy.git

    proxy:
      url: git@github.com:msplat/gateway-proxy.git

  auth:
    configuration:
      url: git@github.com:msplat/auth-configuration.git
      variables:
        domain: sso.msplat.test

    api:
      url: git@github.com:msplat/auth-api.git

    ui:
      url: git@github.com:msplat/auth-ui.git
